name: Backend Deploy (Staging)

on:
  push:
    branches: [staging]
    paths:
      - "backend/**"
      - ".github/workflows/backend-staging.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: windows-latest
    name: Build Backend (.NET)
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"
      - name: Restore dependencies
        run: dotnet restore backend/Gifty.Api/Gifty.Api.csproj
      - name: Build
        run: dotnet build backend/Gifty.Api/Gifty.Api.csproj --configuration Release
      - name: Publish
        run: dotnet publish backend/Gifty.Api/Gifty.Api.csproj -c Release -o ./publish
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-publish
          path: ./publish

  test:
    runs-on: windows-latest
    name: Test Backend
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"
      - name: Run Tests
        run: dotnet test backend/Gifty.sln --configuration Release
        env:
          UseTestAuth: "true"
          ASPNETCORE_ENVIRONMENT: "Development"

  deploy:
    runs-on: windows-latest
    name: Deploy Backend to Azure
    needs: test
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-publish
          path: publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_STAGING }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID_STAGING }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_STAGING }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "gifty-api-staging"
          slot-name: "Production"
          package: ./publish
